language: node_js 
node_js: stable

install: 
- yarn install -g hexo
- yarn install -g gulp 
- yarn install

# - npm install -g gulp

script: 
- hexo g

after_script: 
- cd ./public 
- git init 
- git config user.name “ferryvan” 
- git config user.email “1156709213@qq.com” 
- git add . 
- git commit -m “Update docs with TRAVIS-CI.” 
- git push --force --quiet "https://aa654290ea150df1cf0efca66520232cff5447a0@github.com/ferryvan/ferryvan.github.io.git" master:master

branches: 
only: 
- hexo 
env: 
global: 
- GH_REF: github.com/ferryvan/ferryvan.github.io.git 
