language: node_js 
node_js: stable

install: 
- npm install -g cnpm
- cnpm install -g gulp
- cnpm install

# - npm install -g gulp

script: 
- hexo g

after_script: 
- cd ./public 
- git init 
- git config user.name "ferryvan"
- git config user.email "1156709213@qq.com" 
- git add . 
- git commit -m "Update docs with TRAVIS-CI." 
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


branches: 
only: 
- blog 
env: 
global: 
- GH_TOKEN: 12d75f023c0e23a4346740306b48e463720c1df1
- GH_REF: github.com/ferryvan/ferryvan.github.io.git 
