language: node_js 
node_js: stable

install: 
- npm install -g cnpm
- cnpm install -g gulp
- cnpm install


# - npm install -g gulp

script: 
- hexo g

after_script: 
- cd ./public 
- git init 
- git config user.name "ferryvan"
- git config user.email "1156709213@qq.com" 
- git add . 
- git commit -m "Update docs with TRAVIS-CI." 
- git push --force --quiet "https://${mytoken}@github.com/ferryvan/ferryvan.github.io.git" master:master

branches: 
only: 
- blog 
