language: node_js 
node_js: stable

install: 
- npm install -g cnpm
- cnpm install -g gulp
- cnpm install

# - npm install -g gulp

script: 
- hexo d -g

after_script: 

branches: 
only: 
- blog 
env: 
global: 
- GH_REF: github.com/ferryvan/ferryvan.github.io.git 
